### ISSUE TITLE
Support ndarrays in json dictable

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoConf#19]
I am outputting a `Clocker2D` object (from autocti) to a .json file as follows:

```
clocker = ac.Clocker2D(
    iterations=5,
    parallel_express=5,
    serial_express=5
)

clocker.output_to_json(file_path="cti_clocker.json")
```

One of the internal variables is a ndarray, which is not output correctly:

```
{
    "type": "VIS_CTI_Autocti.VIS_CTI_Clocker.two_d.Clocker2D",
    "iterations": 5,
    "parallel_roe": {
        "type": "SHE_ArCTICPy.roe.ROE",
        "dwell_times": {
            "type": "numpy.ndarray"
        },
        "empty_traps_between_columns": true,
        "empty_traps_for_first_transfers": false,
        "force_release_away_from_readout": true,
        "use_integer_express_matrix": false
    },
    "parallel_express": 5,
    "parallel_offset": 0,
    "parallel_window_start": 0,
    "parallel_window_stop": -1,
    "parallel_poisson_traps": false,
    "parallel_fast_pixels": null,
    "serial_roe": {
        "type": "SHE_ArCTICPy.roe.ROE",
        "dwell_times": {
            "type": "numpy.ndarray"
        },
        "empty_traps_between_columns": true,
        "empty_traps_for_first_transfers": false,
        "force_release_away_from_readout": true,
        "use_integer_express_matrix": false
    },
    "serial_express": 5,
    "serial_offset": 0,
    "serial_window_start": 0,
    "serial_window_stop": -1,
    "serial_fast_pixels": null,
    "verbosity": 0,
    "poisson_seed": -1,
    "euclid_orientation_hack": false
}
```

It is specifically this part which is the issue:

```
        "type": "SHE_ArCTICPy.roe.ROE",
        "dwell_times": {
            "type": "numpy.ndarray"
        },
```

Could we add support for ndarrays to the dictable object?

**Comment by rhayes777** [comment]
So do we want lists of lists of objects or a reference to some fixed numpy array?

**Comment by Jammy2211** [comment]
Basically, if I try to load the .json file I get the following error:

`ac.Clocker2D.from_json(file_path="cti_clocker.json")`

```
Traceback (most recent call last):
  File "clocker_json.py", line 11, in <module>
    ac.Clocker2D.from_json(file_path="cti_clocker.json")
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoEden/build_eden/VIS_CTI/VIS_CTI_Autoconf/python/VIS_CTI_Autoconf/dictable.py", line 70, in from_json
    return cls.from_dict(cls_dict=cls_dict)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoEden/build_eden/VIS_CTI/VIS_CTI_Autoconf/python/VIS_CTI_Autoconf/dictable.py", line 52, in from_dict
    **{name: Dictable.from_dict(value) for (name, value) in cls_dict.items()}
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoEden/build_eden/VIS_CTI/VIS_CTI_Autoconf/python/VIS_CTI_Autoconf/dictable.py", line 52, in <dictcomp>
    **{name: Dictable.from_dict(value) for (name, value) in cls_dict.items()}
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoEden/build_eden/VIS_CTI/VIS_CTI_Autoconf/python/VIS_CTI_Autoconf/dictable.py", line 52, in from_dict
    **{name: Dictable.from_dict(value) for (name, value) in cls_dict.items()}
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoEden/build_eden/VIS_CTI/VIS_CTI_Autoconf/python/VIS_CTI_Autoconf/dictable.py", line 52, in <dictcomp>
    **{name: Dictable.from_dict(value) for (name, value) in cls_dict.items()}
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoEden/build_eden/VIS_CTI/VIS_CTI_Autoconf/python/VIS_CTI_Autoconf/dictable.py", line 51, in from_dict
    return cls(
TypeError: ndarray() missing required argument 'shape' (pos 1)
```

Forgot to put that part in the description... but whatever will fix that.
